language: node_js
node_js:
  - "14.18.1"
dist: trusty
sudo: required
addons:
  apt:
    packages:
      - dpkg
  chrome: stable
branches:
  only:
    - main
before_script:
  - npm install -g @angular/cli
script:
  - ng lint better-item-toolbar
  - ng test better-item-toolbar --watch=false --browsers=ChromeHeadless --code-coverage=true
  - ng build better-item-toolbar --configuration production
  - ng build demo --configuration production --base-href https://tfaster.github.io/better-item-toolbar/
after_success:
  - codecov
deploy:
  provider: pages
  skip_cleanup: true # To avoid cleanup of the artifact generated during script
  github_token: $GITHUB_TOKEN # Provided as an environment variable in travis
  local_dir: dist/demo
  on:
    branch: main
